### ISSUE TITLE
Installation failed during preinstall step. Please check log for details

### ISSUE THREAD

**Issue by tresf** [qzind/tray#638]
Installing with certain Java versions fail with the following.

> Installation failed during preinstall step. Please check log for details

There appears to be something going wrong with the `preinstall` step.  Running it manually works fine.

**Comment by tresf** [comment]
Somehow we missed double quotes in the 2.1.0 installer.  I'm quite puzzled this hasn't been reported before, but I'll make a 2.1.0+2 patch release and put it on the downloads page.  Fixed via https://github.com/qzind/tray/commit/b4e24fd9e2a0fe89ee0b0a89bad41ecdba231349

**Comment by mlscherer** [comment]
Hello @tresf , I'm having, apparently the same error while trying to install 2.1.6.

I updated Java on the computer to the latest version and still the same error happened.

I was unable to copy the whole text, but I hope this helps:
<img width="473" alt="Captura de Tela 2022-12-05 às 11 37 14" src="https://user-images.githubusercontent.com/41930365/205663663-6a44a1ee-4730-44b1-a44e-bae48c92e9ea.png">

**Comment by tresf** [comment]
@mlscherer,

Can you please try the 2.2.1 beta version from our downloads page?  This ships with it's own version of Java and fixes most installation issues.

**Comment by mlscherer** [comment]
Hi @tresf. Sorry for the delay. I did that and for now, 2.2.1 installed and is working fine.

Thank you!

**Comment by tresf** [comment]
@mlscherer thanks for the update.  Note, QZ Tray 2.2.2 will list as the next stable release which will come with bundled Java.

**Comment by mlscherer** [comment]
Nice @tresf ! When can we expect that release?

**Comment by tresf** [comment]
@mlscherer we'll be starting QA on it today, so as long as there's no blockers, next week.
